### ISSUE TITLE
I can not start the container via GNS3 interface

### ISSUE THREAD

**Issue by atomus1990** [nokia/srlinux-container-image#3]
If I use docker-run on the GNS3 server, I can start the container but if I start it via GNS3 interface, it exits.

Observations: GNS3 uses /gns3/init.sh 

8e0943229be5   ghcr.io/nokia/srlinux:latest   "/gns3/init.sh /tini…"   3 hours ago   Exited (137) 3 hours ago             loving_faraday

 docker logs 8e0943229be5
su: unknown user user:user

GNS3 log:
INFO docker_vm.py:549 Docker container 'ghcr.io-nokia-srlinux-1' fix ownership, state = exited

First container below is started using directly docker run.

NAMES
3b20d2e9a743   ghcr.io/nokia/srlinux          "/tini -- fixuid -q …"   18 seconds ago   Up 16 seconds                        srlinux_container
8e0943229be5   ghcr.io/nokia/srlinux:latest   "/gns3/init.sh /tini…"   3 hours ago      Exited (137) 3 hours ago             loving_faraday

It could be a GNS3 issue, I opened here also: https://www.gns3.com/community/discussions/ghcr-io-nokia-srlinux , but at the same time I tried multiple docker containers, and this is the only one where I noticed this issue

**Comment by hellt** [comment]
Hi @atomus1990 
SR Linux container image requires to be run with `privileged` escalation or set the right network capabilities.
afaik GNS doesn't allow to use either of these modes.

Feel free to reopen this if new info is needed, but I believe SR Linux can't quite run on GNS/EVE without privileged support at this moment
